<a href="https://colab.research.google.com/github/thessafuzaro/Redes_Neurais/blob/main/aula_28_04_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
import pandas as pd

In [22]:
x=[1,2,3,4,5]
y=[2,3,6,8,9]
Lista = [x,y]
Vetor=np.array(Lista)
dataframe = pd.DataFrame({'x':x,'y':y})
#x_array=np.array(x)
x_array=np.array(x).reshape(-1,1)

In [23]:
print(x)
print(y)
print(Lista)
print(Vetor)
print(dataframe)
print(x_array)

[1, 2, 3, 4, 5]
[2, 3, 6, 8, 9]
[[1, 2, 3, 4, 5], [2, 3, 6, 8, 9]]
[[1 2 3 4 5]
 [2 3 6 8 9]]
   x  y
0  1  2
1  2  3
2  3  6
3  4  8
4  5  9
[[1]
 [2]
 [3]
 [4]
 [5]]


In [24]:
N=[8,9,10,11,12]
M=[8,9,10,11,12]
for i in range(2,N): #desse jeito ele começa do zero (N) e se entrar com o valor ele começa de onde vc escolhe (2,N)
  for j in range(2,M):
    print('i=',i,'j=',j)

i= 0 j= 0
i= 0 j= 1
i= 0 j= 2
i= 1 j= 0
i= 1 j= 1
i= 1 j= 2
i= 2 j= 0
i= 2 j= 1
i= 2 j= 2
i= 3 j= 0
i= 3 j= 1
i= 3 j= 2
